todo/todo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("todoprojectapp.urls")),
]
if settings . DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todo/todoprojectapp/urls.py
from django.urls import path, include

from todoprojectapp import views
app_name='todoprojectapp'

urlpatterns = [

    path('',views.home,name='home'),
    path('delete/<int:taskid>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),
    path('cbvhome/',views.TaskListView.as_view(),name='cbvhome'),
    path('cbvdetail/<int:pk>/',views.TaskDetailView.as_view(),name='cbvdetail'),
    path('cbvupdate/<int:pk>/',views.TaskupdateView.as_view(),name='cbvupdate'),
    path('cbvdelete/<int:pk>/',views.TaskDeleteView.as_view(),name='cbvdelete'),

]

todo/todoprojectapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    task_date=models.DateField()
def __str__(self):
    return self.name

todo/todoprojectapp/forms.py
from . models import Task
from django import forms

class TodoForm(forms.ModelForm):
    class Meta:
        model=Task
        fields=['name','priority','task_date']

todo/todoprojectapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from . models import Task
from . forms import TodoForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView
# Create your views here.

class TaskListView(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'task'
class TaskDetailView(DetailView):
    model = Task
    template_name = 'detail.html'
    context_object_name = 'task'
class TaskupdateView(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('name','priority','task_date')

    def get_success_url(self):
        return reverse_lazy('todoprojectapp:cbvdetail',kwargs={'pk':self.object.id})

class TaskDeleteView(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todoprojectapp:cbvhome')

def home(request):
    task1=Task.objects.all()
    if request.method=='POST':
        name=request.POST.get('task','')
        priority=request.POST.get('priority','')
        task_date=request.POST.get('task_date','')
        task=Task(name=name,priority=priority,task_date=task_date)
        task.save()
    return render(request,"home.html",{'task':task1})
def delete(request,taskid):
    task=Task.objects.get(id=taskid)
    if request.method=='POST':
        task.delete()
        return redirect('/')
    return render(request,'delete.html')
def update(request,id):
    task=Task.objects.get(id=id)
    f=TodoForm(request.POST or None,instance=task)
    if f.is_valid():
        f.save()
        return redirect('/')
    return render(request,'edit.html',{'f':f,'task':task})

todo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

todo/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
    <div class="card.header">
        <div class="card-title">
            Task Delete
        </div>
        <div class="card-body">
          <form method="POST">
          {% csrf_token %}
            <p>Are you sure this task is done?</p>
            <button type="submit">Confirm</button>
          </form>
        </div>
    </div>
</div>
{% endblock %}

todo/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="col-md-6">
            <h4>Task to be completed</h4>

            <div class="shadow card">
                <div class="card-body">
                    <h5 class="card-title">{{task.name}}</h5>
                    <p><b>{{task.priority}}</b></p>
                    <p><b>{{task.task_date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoprojectapp:delete' task.id %}">Done</a>
                    <a class="btn btn-danger" href="{% url 'todoprojectapp:update' task.id %}">UPDATE</a>
                </div>
            </div>

</div>
<br>
    {% endblock %}

todo/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
  {% csrf_token %}
  {{ f.as_p }}
  <button type="submit">Confirm</button>
</form>
{% endblock %}

todo/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col_md_12">
            <div class="banner">
                <div class="banner-text">
                    <h1>ToDo</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="POST" class="p-3 shadow">
            {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" name="task" placeholder="taskname">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="priority" placeholder="enter your priority">
                </div><br>
                <div class="form-group">
                    <input type="date" class="form-control" name="task_date" placeholder="enter your date">
                </div><br>
                    <input type="submit" class="btn btn-success">
            </form>




        </div>
        <div class="col-md-6">
            <h4>Task to be completed</h4>
            {% for i in task %}
            <div class="shadow card">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p><b>{{i.priority}}</b></p>
                    <p><b>{{i.task_date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoprojectapp:delete' i.id %}">Done</a>
                    <a class="btn btn-danger" href="{% url 'todoprojectapp:update' i.id %}">UPDATE</a>
                </div>
            </div>
            <br>
            {% endfor %}

        </div>
    </div>
</div>

{% endblock %}

todo/templates/update.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
    <div class="card.header">
        <div class="card-title">
            Task Update
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Confirm</button>
            </form>
        </div>
    </div>
</div>

 {% endblock %}